server:
  port: 10010
spring:
    application:
      name: gateway
    cloud:
      gateway:
        routes:
          - id: ride-service  # name of the route
            uri: lb://ride-service
            predicates:       # routing rule
              - Path=/ride-rpc/**
          - id: ride-client
            uri: lb://ride-application
            predicates: # routing rule
              - Path=/ride-client/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
